#!/usr/bin/python

import os, argparse, hashlib, email, glob, sqlite3

parser = argparse.ArgumentParser(description='Parses emails into an SQLite database, and optionally renders static HTML files.')

parser.add_argument('-p', '--pattern', dest='pattern', action='store', default='*',
                   help='glob pattern (including path) that has to be matched for a file to be parsed')
                   
parser.add_argument('-r', '--render', dest='render', action='store_true',
                   help='render static HTML files using the template files in templates/')

args = parser.parse_args()
options = vars(args)

file_list = glob.glob(options['pattern'])

for email_file in file_list:
	message = email.message_from_file(open(email_file))
	
	if message['message-id'] is None:
		print "%s is not a valid e-mail file." % email_file
	else:
		if 'subject' not in message or message['subject'] is None:
			subject = ""
		else:
			subject = message['subject']
		
		sha1_hash = hashlib.sha1("%s/%s/%s/%s" % (message['from'], message['to'], message['message-id'], subject)).hexdigest()
			
